// <auto-generated />
using System;
using MMT.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MMT.Migrations
{
    [DbContext(typeof(SSE_TestContext))]
    partial class SSE_TestContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MMT.Models.Order", b =>
                {
                    b.Property<int>("Orderid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ORDERID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool?>("Containsgift")
                        .HasColumnType("bit")
                        .HasColumnName("CONTAINSGIFT");

                    b.Property<string>("Customerid")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("CUSTOMERID");

                    b.Property<DateTime?>("Deliveryexpected")
                        .HasColumnType("date")
                        .HasColumnName("DELIVERYEXPECTED");

                    b.Property<DateTime?>("Orderdate")
                        .HasColumnType("date")
                        .HasColumnName("ORDERDATE");

                    b.Property<string>("Ordersource")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("ORDERSOURCE");

                    b.Property<string>("Shippingmode")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("SHIPPINGMODE");

                    b.HasKey("Orderid");

                    b.ToTable("ORDERS");
                });

            modelBuilder.Entity("MMT.Models.Orderitem", b =>
                {
                    b.Property<int>("Orderitemid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ORDERITEMID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Orderid")
                        .HasColumnType("int")
                        .HasColumnName("ORDERID");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(9,2)")
                        .HasColumnName("PRICE");

                    b.Property<int?>("Productid")
                        .HasColumnType("int")
                        .HasColumnName("PRODUCTID");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("QUANTITY");

                    b.Property<bool?>("Returnable")
                        .HasColumnType("bit")
                        .HasColumnName("RETURNABLE");

                    b.HasKey("Orderitemid");

                    b.HasIndex("Orderid");

                    b.HasIndex("Productid");

                    b.ToTable("ORDERITEMS");
                });

            modelBuilder.Entity("MMT.Models.Product", b =>
                {
                    b.Property<int>("Productid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PRODUCTID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Colour")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("COLOUR");

                    b.Property<decimal?>("Packheight")
                        .HasColumnType("decimal(9,2)")
                        .HasColumnName("PACKHEIGHT");

                    b.Property<decimal?>("Packweight")
                        .HasColumnType("decimal(8,3)")
                        .HasColumnName("PACKWEIGHT");

                    b.Property<decimal?>("Packwidth")
                        .HasColumnType("decimal(9,2)")
                        .HasColumnName("PACKWIDTH");

                    b.Property<string>("Productname")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PRODUCTNAME");

                    b.Property<string>("Size")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("SIZE");

                    b.HasKey("Productid");

                    b.ToTable("PRODUCTS");
                });

            modelBuilder.Entity("MMT.Models.Orderitem", b =>
                {
                    b.HasOne("MMT.Models.Order", "Order")
                        .WithMany("Orderitems")
                        .HasForeignKey("Orderid")
                        .HasConstraintName("FK__ORDERITEM__ORDER__60A75C0F");

                    b.HasOne("MMT.Models.Product", "Product")
                        .WithMany("Orderitems")
                        .HasForeignKey("Productid")
                        .HasConstraintName("FK__ORDERITEM__PRODU__619B8048");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MMT.Models.Order", b =>
                {
                    b.Navigation("Orderitems");
                });

            modelBuilder.Entity("MMT.Models.Product", b =>
                {
                    b.Navigation("Orderitems");
                });
#pragma warning restore 612, 618
        }
    }
}
